name: DMOSS
favicon: null
layout_spectrum: 0.4693437304813415
typography_spectrum: 0.17898
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.5836300272494555
  lightness: 0.6438070207368582
  saturation: 0.853431727970019
  rhythmicContrast: 0.41314005153253675
purpose: []
